# Generated by Django 5.2.7 on 2025-10-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('7', 'پایه هفتم'), ('8', 'پایه هشتم'), ('9', 'پایه نهم')], max_length=1)),
                ('classroom', models.CharField(choices=[('701', '۷۰۱'), ('702', '۷۰۲'), ('801', '۸۰۱'), ('802', '۸۰۲'), ('901', '۹۰۱'), ('902', '۹۰۲')], max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'grade', 'classroom')},
            },
        ),
    ]
